FROM python:slim


RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
RUN pip install --upgrade pip

RUN mkdir -p capture 
WORKDIR "/capture"

RUN pip install flask
RUN pip install numpy --upgrade
RUN pip install opencv-python

ENV PYTHONPATH /usr/lib/python3/dist-packages

ENTRYPOINT ["tail", "-f", "/dev/null"]
